
Raw Benchmark Output
====================

Running Convolution 3D on Octuplets using Bohrium/GPU
    commit: `#fa00a842de7b795abe88cb33f4696b92db6a08df <https://bitbucket.org/bohrium/bohrium/commits/fa00a842de7b795abe88cb33f4696b92db6a08df>`_,
    time: 2015-03-15 04:05:47.331624.

    command: ``python benchmark/Python/convolve_3d.py --size=100 --bohrium=True``

Run 00
~~~~~~
    stdout::

        N/A

    stderr::

        python: can't open file 'benchmark/Python/convolve_3d.py': [Errno 2] No such file or directory
        



Run 01
~~~~~~
    stdout::

        N/A

    stderr::

        python: can't open file 'benchmark/Python/convolve_3d.py': [Errno 2] No such file or directory
        



Run 02
~~~~~~
    stdout::

        N/A

    stderr::

        python: can't open file 'benchmark/Python/convolve_3d.py': [Errno 2] No such file or directory
        



