
Raw Benchmark Output
====================

Running Convolution 3D on Octuplets using Bohrium/CPU
    commit: `#d2b549b1c91deaf87ba4728fce670065aeeaac12 <https://bitbucket.org/bohrium/bohrium/commits/d2b549b1c91deaf87ba4728fce670065aeeaac12>`_,
    time: 2015-03-06 04:05:53.187426.

    command: ``python benchmark/Python/convolve_3d.py --size=100 --bohrium=True``

Run 00
~~~~~~
    stdout::

        N/A

    stderr::

        python: can't open file 'benchmark/Python/convolve_3d.py': [Errno 2] No such file or directory
        



Run 01
~~~~~~
    stdout::

        N/A

    stderr::

        python: can't open file 'benchmark/Python/convolve_3d.py': [Errno 2] No such file or directory
        



Run 02
~~~~~~
    stdout::

        N/A

    stderr::

        python: can't open file 'benchmark/Python/convolve_3d.py': [Errno 2] No such file or directory
        



